### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by luzpaz** [hyarion/FreeCAD_InspectWidgets#1]
git cloned into `~/.FreeCAD/Mod`
restart FC  
no joy :cry:

**Comment by hyarion** [comment]
@luzpaz Strange, I've tested that and it works for me (on mac though)

Check if you get this menu item (view->panels->inspect widgets):
![image](https://user-images.githubusercontent.com/349748/107966379-0ababb80-6fac-11eb-87e4-20747a6f82a7.png)

If not, do you get any error messages in the console?
And can you post your freecad info?

**Comment by luzpaz** [comment]
Nice!!!

**Comment by turn211** [comment]
Wow you read my mind with your Mod! Handy to reverse engineer stylesheets. Very Cool! Working great on Windows 10.

**Comment by hyarion** [comment]
@turn211 Feel free to suggest new features that you would like to see implemented!
